---
title: 'MetaboAnalystR 3 workflow: Enhanced throughput of Global Metabolomics Data
  Analysis'
author: "Zhiqiang Pang, Jasmine Chong and Jeff Xia"
date: "11/04/2020"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

### 1. Introduction of MetaboAnalystR 3.0

**MetaboAnalystR 3.0** is aimed to optimize three important points for the whole pipeline. First, raw spectral processing parameters optimization. Second, we have enhanced the ability to correct batch effect by organising different algorithm. In addition, strengthened support for functional interpretation directly from m/z peaks via mummichog2 (PMID: 23861661) by integrating RT to refine the grouping of signals. To demonstrate this new functionality, we provide the "MetaboAnalystR 3.0 Workflow: Enhanced Global Metabolomics Analysis" vignette here. 

In this vignette, we are going to perform end-to-end metabolomics data analysis on (Case 1) example samples of clinical IBD samples from <https://www.ibdmdb.org/> and (Case 2) standards' mixture (PMID: 29907290). Case 1 is series facel samples from IBD (including CD and UC) and nonIBD controls. Case 2 is a dataset comprimised of 1100 standard compounds under the detection of UPLC-Q/E.

### 2. Case Study 1
Inflammatory bowel diseases, which include Crohn’s disease and ulcerative colitis, have affected several million individuals around the world. Jason L. et al. have performed a longtitude multiomics study on the role of microbiome in the pathogenesis of IBD. Metabolomics study on the facal samples is introduced here for benchmark study of this noval parameters optimization pipeline.

